blank_issues_enabled: false
contact_links:
  - name: XLink Kai Troubleshooting/Support 
    url: https://discord.gg/UyyjNpa
    about: For support and technical issues, please come to our Discord server.
